version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:

  build-and-test:

    docker:

      - image: cimg/openjdk:8.0.422

    steps:

      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      

      - run:
          name: Convert Checkstyle XML to HTML
          command: |
            curl -sS https://github.com/checkstyle/checkstyle-xml-reporter/releases/download/v1.4/checkstyle-xml-reporter-1.4.jar > checkstyle-xml-reporter.jar
            java -jar checkstyle-xml-reporter.jar -i target/checkstyle-reports/checkstyle-result.xml -o target/checkstyle-reports/checkstyle-report.html

      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle-reports
      
      - codecov/upload

      
  
workflows:
  sample: 
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master




    