version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:

  build-and-test:

    docker:

      - image: cimg/openjdk:8.0.422

    steps:

      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      

      
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle-reports
      
      - codecov/upload

      
  
workflows:
  sample: 
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master




    