version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:

  build-and-test:

    docker:

      - image: cimg/openjdk:8.0.422

    steps:

      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - run:
          name: Execute Checkstyle
          command: mvn checkstyle:check
      
      - run:
          name: Génère Checkstyle Badge
          command: |
            ./checkstyle-badge.sh
      
      - run:
          name: Update README avec Checkstyle Badge
          command: |
            badge_url=$(cat target/checkstyle/checkstyle-badge-url.txt)
            sed -i "s|https://img.shields.io/badge/.*|$badge_url|" README.md
            git config --global user.email "julien-jamme@outlook.com"
            git config --global user.name "Daimbow"
            git commit -am "Update Checkstyle badge"
            git push

      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle-reports
      
      - codecov/upload

      
  
workflows:
  sample: 
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master




    