name: Javadoc Generation and Deployment

on: 
  push:
    branches:
      - master 

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8.0.432+6'

      - name: Build with Maven Javadoc
        run: mvn -B clean javadoc:javadoc

      - name: Copy Javadoc to deployment directory
        run: |
          mkdir -p target/reports/apidocs
          cp -r target/site/apidocs/* target/reports/apidocs/

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs

