name: Javadoc Generation and Deployment

on: [push]

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8.0.432+6'

      - name: Build with Maven JavaDoc
          run: |
            mvn -B javadoc:javadoc

      - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.DOC_TOKEN }}
            publish_dir: ./target/reports/apidocs
            