name: Javadoc and Checkstyle Generation and Deployment

on: [push]

jobs:
  generate-javadoc-and-checkstyle:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8.0.432+6'

      - name: Build with Maven Javadoc and Checkstyle
        run: mvn -B clean javadoc:javadoc checkstyle:checkstyle

      - name: Copy Checkstyle report to Javadoc directory
        run: |
          mkdir -p target/reports/apidocs/checkstyle
          cp target/checkstyle-*.xml target/reports/apidocs/checkstyle/
      - name: Deploy Javadoc and Checkstyle to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs

      - name: Clean-up
        run: rm -rf ./target/reports/apidocs