name: Javadoc Generation and Checkstyle

on:
  push:
    branches:
      - master

jobs:
  generate-javadoc-and-checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8.0.432+6'

      - name: Install XSLT processor
        run: sudo apt-get update && sudo apt-get install -y xsltproc

      - name: Build with Maven Javadoc and Checkstyle
        run: mvn -B clean javadoc:javadoc checkstyle:checkstyle

      - name: Generate Checkstyle HTML report
        run: |
          mvn checkstyle:checkstyle
          mkdir -p ./target/reports/checkstyle/html
          xsltproc -o ./target/reports/checkstyle/html/checkstyle-report.html ./target/checkstyle-*.xml

      - name: List files in the target directory
        run: ls -R ./target

      - name: Deploy Javadoc and Checkstyle HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs
