name: Javadoc génération et déploiement

on: 
  push:
    branches:
      - master

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8.0.432+6'

      - name: Build avec Maven Javadoc
        run: mvn -B javadoc:javadoc

      - name: Déploie Javadoc sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs
